version: 0.2
phases:
  install:
  commands:
    - npm install
  build:
    commands:
      - npm run build
  artifacts:
    files:
      - "**/*"
    base-directory: build
  post_build:
  commands:
    - aws s3 sync build/ s3://code-deployment-bucket-dilshad --delete